import { Router } from "express";
import { BusinessController } from "../controllers/BusinessController";
import { isAuthenticate } from "../middlewares/UserMiddlewares";
import { hasRole, parseImage } from "../middlewares/GlobalMiddleware";
import { createBusinessRules, existBusiness, existBusinesses, registerUserRules, updateActive, updateBusiness } from "../middlewares/BusinessMiddleware";
import { handleInputErrors } from "../utils/validator";
import { MEMBER_ROLES } from "../models/Member";

const router: Router = Router();
router.use(isAuthenticate, hasRole(MEMBER_ROLES.OWNER));
router.get('/my-business', existBusinesses, handleInputErrors, BusinessController.getBusiness);
router.get('/:businessId', existBusiness, handleInputErrors, BusinessController.getBusinessById);
router.post('/create', createBusinessRules, handleInputErrors, BusinessController.createBusiness);
router.post('/register-user', registerUserRules, handleInputErrors, BusinessController.registerUser);
router.put('/update/:businessId', existBusiness, updateBusiness, handleInputErrors, BusinessController.updateBusiness);
router.patch('/update/:businessId/logo', existBusiness, parseImage, handleInputErrors, BusinessController.uploadLogo);
router.patch('/update/:businessId/cover', existBusiness, parseImage, handleInputErrors, BusinessController.uploadCover);
router.delete('/delete/:businessId', existBusiness, handleInputErrors, BusinessController.deleteBusiness);
router.patch('/update/:businessId/isActive', existBusiness, updateActive, handleInputErrors, BusinessController.updateIsActive);
export default router;